language: rust
jobs:
  allow_failures:
    - script: cargo clippy --verbose --package osproto -- -D warnings
  include:
    - install: rustup component add rustfmt
      script: cargo fmt -- --check
      name: "Check formatting"
    - install: rustup component add clippy
      script: cargo clippy --verbose --package osproto -- -D warnings
      name: "Check clippy warnings (non-voting)"
    - script: cargo test --verbose
      name: "Run unit tests"
    - script: cargo doc --verbose
      name: "Build documentation"
